#' Visualize data points for specific Wells over time
#'
#' @param input A list generated by readPlate()
#' @param sample A Character string for the sample you'd like to see (either a sample name or #blank)
#' @param measure A character string (or part of it) that identifies the measurement of interest (e.g. "Absorbance" or "Abs", "GFP")
#'
#' @export
#'


checkReplicates <- function(input, sample, measure = "Absorbance") {

  parameter <-  stringr::str_subset(colnames(input$rawdata), pattern = measure)
  subset_col <- dplyr::if_else(stringr::str_detect(sample,"#"), "blank_wells", "sample_wells")

  query_wells <- input$plate_layout_parsed %>%
    dplyr::filter(if (stringr::str_starts(sample,"#")) blank == sample else variable == sample) %>%
    dplyr::select(.data[[subset_col]]) %>%
    unlist() %>%
    unique()

  input$rawdata %>%
    dplyr::filter(Well %in% query_wells) %>%
    dplyr::group_by(Repeat) %>%
    dplyr::mutate(mean = mean(.data[[parameter]])) %>%
    ggplot2::ggplot(ggplot2::aes(x = Repeat, y = .data[[parameter]], label = Well, group = Well, color = Well)) +
    ggplot2::geom_line() +
    ggplot2::geom_text() +
    ggplot2::geom_line(ggplot2::aes(y = mean), linetype = "dashed", color = "grey30") +
    ggplot2::ggtitle(glue::glue("Checking {parameter} for sample {sample}")) +
    ggplot2::theme_minimal()
}
