#' @importFrom magrittr %>%
utils::globalVariables(c(".data",
                         "Condition",
                         "Samples",
                         "Wells",
                         "variable",
                         "Well",
                         "Absorbance @ 600 (A)",
                         "Mean",
                         "Repeat",
                         "Sample",
                         "Well",
                         "condition",
                         "sample",
                         "samples",
                         "Replicate",
                         "Variable",
                         "BiologicalRepMean",
                         "BiologicalRepSD",
                         ".",
                         "blank",
                         "value",
                         "normalized",
                         '` `',
                         "Col",
                         "Row",
                         "X",
                         "X.1",
                         "X.2",
                         "index",
                         "Cycle",
                         "Time(s)",
                         "Plate",
                         "Barcode",
                         "Time",
                         "Temperature(¡C)",
                         "...51",
                         "A1",
                         "F8",
                         "Absorbance"))

