#' @importFrom magrittr %>%
utils::globalVariables(c(".data",
                         "Condition",
                         "Samples",
                         "Wells",
                         "variable",
                         "Well",
                         "Absorbance @ 600 (A)",
                         "Mean",
                         "Repeat",
                         "Sample",
                         "Well",
                         "condition",
                         "sample",
                         "samples",
                         "Replicate",
                         "Variable",
                         "BiologicalRepMean",
                         "BiologicalRepSD",
                         "."))

