#' Converts a biologicalRep table from long to wide
#' @param bioReps a table generated by biologicalReps()
#' @export

makeWideTable <- function(bioReps) {

  wideBioReps <- bioReps |>
    dplyr::group_by(Repeat, Condition) |>
    dplyr::select(-BiologicalRepSD) |>
    tidyr::pivot_wider(names_from = Sample, values_from = BiologicalRepMean) |>
    dplyr::relocate(Repeat)

  return(wideBioReps)
}
